name: test build

on:
  push:
    branches:
      - "**"

jobs:
  build-app:
    runs-on: macos-latest
    steps:
      - name: Use xcode 15.3
        run: sudo xcode-select -s /Applications/Xcode_15.3.app
        shell: bash

      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore node_modules cache
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}-node_modules

      - name: Install dependencies
        run: yarn install

      - name: Save node_modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}-node_modules

      - name: lint
        run: yarn lint

      - name: test
        run: yarn test
